//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activos()
        {
            this.Asignaciones = new HashSet<Asignaciones>();
        }
    
        public int idActivo { get; set; }
        public string nombreActivo { get; set; }
        public string descripcion { get; set; }
        public byte[] foto { get; set; }
        public Nullable<decimal> precioInicial { get; set; }
        public Nullable<System.DateTime> fechaCompra { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public Nullable<int> idEstadoActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asignaciones> Asignaciones { get; set; }
        public virtual EstadoActivos EstadoActivos { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
