//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignaciones
    {
        public int idAsignacion { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idActivo { get; set; }
        public Nullable<System.DateTime> fechaInicialAsignacion { get; set; }
        public Nullable<System.DateTime> fechafinalAsignacion { get; set; }
    
        public virtual Activos Activos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
