//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAsignaciones
    {
        public int IdAsignacion { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdActivo { get; set; }
        public Nullable<System.DateTime> FechaInicialAsignacion { get; set; }
        public Nullable<System.DateTime> FechafinalAsignacion { get; set; }
    
        public virtual Activos Activos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
