//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activo()
        {
            this.Depreciacions = new HashSet<Depreciacion>();
            this.THAsignaciones = new HashSet<THAsignacione>();
            this.THReparaciones = new HashSet<THReparacione>();
        }
    
        public int IdActivo { get; set; }
        public string CodActivo { get; set; }
        public int Categoria { get; set; }
        public string Descripcion { get; set; }
        public decimal PrecioInicial { get; set; }
        public decimal PrecioActual { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public int Proveedor { get; set; }
        public int EstadoActivo { get; set; }
        public int Garantia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Depreciacion> Depreciacions { get; set; }
        public virtual Categoria Categoria1 { get; set; }
        public virtual EstadoActivo EstadoActivo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THAsignacione> THAsignaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THReparacione> THReparaciones { get; set; }
        public virtual Proveedore Proveedore { get; set; }
    }
}
