//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depreciacion
    {
        public int IdDepreciacion { get; set; }
        public int Activo { get; set; }
        public System.DateTime FechaDepreciacion { get; set; }
        public double MontoDepreciacion { get; set; }
        public double Valor { get; set; }
    
        public virtual Activo Activo1 { get; set; }
    }
}
