//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAsignacione
    {
        public int IdAsignacion { get; set; }
        public int IdUsuario { get; set; }
        public int IdActivo { get; set; }
        public System.DateTime FechaInicialAsignacion { get; set; }
        public System.DateTime FechafinalAsignacion { get; set; }
    
        public virtual Activo Activo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
