//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class THReparacione
    {
        public int IdReparacion { get; set; }
        public int IdActivo { get; set; }
        public System.DateTime FechaInicialReparacion { get; set; }
        public System.DateTime FechafinalReparacion { get; set; }
    
        public virtual Activo Activo { get; set; }
    }
}
